steps:
- name: 'gcr.io/cloud-builders/mvn'
  dir: budget-web
  id: Package solution
  args:
    - package
- name: 'gcr.io/cloud-builders/docker'
  dir: budget-web
  id: Create container
  args:
    - build
    - -f
    - src/main/docker/Dockerfile.jvm
    - -t
    - gcr.io/${PROJECT_ID}/budget-api:${_VERSION}
    - .
- name: 'gcr.io/cloud-builders/docker'
  id: Push image
  args:
    - push
    - gcr.io/${PROJECT_ID}/budget-api:${_VERSION}
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy app
  args:
    - beta
    - run
    - deploy
    - web
    - --image=gcr.io/${PROJECT_ID}/budget-api:${_VERSION}
    - --platform=managed
    - --region=europe-west1
    - --project=${PROJECT_ID}
    - --service-account=budget@mybudget-monlabo-biz.iam.gserviceaccount.com
    - --set-secrets=PWD=WEB_PWD:latest
timeout: 600s
substitutions:
  _VERSION: '0.2.5'